-- 1. Departments Table
CREATE TABLE Departments (
    Department_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Name   VARCHAR2(100) NOT NULL UNIQUE,
    Department_Head   VARCHAR2(100),
    Created_At        DATE DEFAULT SYSDATE
);


-- 2. Categories Table
CREATE TABLE ProblemCategories (
    Category_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Category_Name   VARCHAR2(100) NOT NULL,
    Department_ID   NUMBER NOT NULL,
    Description     VARCHAR2(255),
    CONSTRAINT fk_category_department FOREIGN KEY (Department_ID)
        REFERENCES Departments(Department_ID)
);

-- 3. Programmers Table
CREATE TABLE Programmers (
    Programmer_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name      VARCHAR2(50) NOT NULL,
    Last_Name       VARCHAR2(50) NOT NULL,
    Email           VARCHAR2(100) UNIQUE,
    Phone           VARCHAR2(20),
    Department_ID   NUMBER NOT NULL,
    Hire_Date       DATE DEFAULT SYSDATE,
    Role            VARCHAR2(50),
    CONSTRAINT fk_programmer_department FOREIGN KEY (Department_ID)
        REFERENCES Departments(Department_ID)
);

-- 4. Customers Table
CREATE TABLE EndUser (
    Customer_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name      VARCHAR2(50) NOT NULL,
    Last_Name       VARCHAR2(50) NOT NULL,
    Email           VARCHAR2(100) UNIQUE,
    Phone           VARCHAR2(20),
    Company_Name    VARCHAR2(100),
    Created_At      DATE DEFAULT SYSDATE
);


-- 5. Tickets Table
CREATE TABLE Tickets (
    Ticket_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EndUser_ID            NUMBER NOT NULL,
    Category_ID            NUMBER NOT NULL,
    Department_ID          NUMBER NOT NULL,
    Assigned_Programmer_ID NUMBER,
    Title                  VARCHAR2(200) NOT NULL,
    Description            VARCHAR2(500),
    Status                 VARCHAR2(20) DEFAULT 'OPEN' CHECK (Status IN ('OPEN','IN PROGRESS','RESOLVED','CLOSED')),
    Priority               VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (Priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    Created_At             DATE DEFAULT SYSDATE,
    Resolved_At            DATE,
    CONSTRAINT fk_ticket_customer FOREIGN KEY (EndUser_ID)
        REFERENCES EndUser(EndUser_ID),
    CONSTRAINT fk_ticket_category FOREIGN KEY (Category_ID)
        REFERENCES ProblemCategories(Category_ID),
    CONSTRAINT fk_ticket_department FOREIGN KEY (Department_ID)
        REFERENCES Departments(Department_ID),
    CONSTRAINT fk_ticket_programmer FOREIGN KEY (Assigned_Programmer_ID)
        REFERENCES Programmers(Programmer_ID)
);

-- 6. Customer_Tickets Table (Optional Many-to-Many)
CREATE TABLE EndUserTickets (
    Customer_Ticket_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EndUser_ID        NUMBER NOT NULL,
    Ticket_ID          NUMBER NOT NULL,
    CONSTRAINT fk_ct_customer FOREIGN KEY (EndUser_ID)
        REFERENCES EndUser(EndUser_ID),
    CONSTRAINT fk_ct_ticket FOREIGN KEY (Ticket_ID)
        REFERENCES Tickets(Ticket_ID)
);


-- 7. Ticket_Comments Table (Optional)
-- =========================
CREATE TABLE Ticket_Comments (
    Comment_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ticket_ID      NUMBER NOT NULL,
    Comment_Text   VARCHAR2(500) NOT NULL,
    Commented_By   VARCHAR2(100), -- Could store Programmer or End user name/ID
    Created_At     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_comment_ticket FOREIGN KEY (Ticket_ID)
        REFERENCES Tickets(Ticket_ID)
);



